<?php
/**
 * PropertiesApi
 * PHP version 7.4.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Katanox API Documentation.
 *
 * The Katanox API allows any travel seller to search and book accommodation.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Katanox\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use InvalidArgumentException;
use Katanox\ApiException;
use Katanox\Configuration;
use Katanox\HeaderSelector;
use Katanox\ObjectSerializer;
use RuntimeException;

/**
 * PropertiesApi Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class PropertiesApi
{
    /** @var string[] */
    public const contentTypes = [
        'getProperties' => [
            'application/json',
        ],
        'getPropertyById' => [
            'application/json',
        ],
        'getRateplanById' => [
            'application/json',
        ],
        'getUnitById' => [
            'application/json',
        ],
    ];

    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index.
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index.
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getProperties.
     *
     * Retrieve the list of contracted properties
     *
     * @param string   $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string[] $property_ids  List of property IDs to be included. When specified, only these properties will be included in the response. The maximum size of this list is 50. (optional)
     * @param string   $contentType   The value for the Content-Type header. Check self::contentTypes['getProperties'] to see the possible values for this operation
     *
     * @return \Katanox\Model\ModelApiError|\Katanox\Model\ModelGetPropertiesResponse|\Katanox\Model\ModelInternalServerError
     *
     * @throws \Katanox\ApiException    on non-2xx response
     * @throws InvalidArgumentException
     */
    public function getProperties($authorization, $property_ids = null, string $contentType = self::contentTypes['getProperties'][0])
    {
        list($response) = $this->getPropertiesWithHttpInfo($authorization, $property_ids, $contentType);

        return $response;
    }

    /**
     * Operation getPropertiesWithHttpInfo.
     *
     * Retrieve the list of contracted properties
     *
     * @param string   $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string[] $property_ids  List of property IDs to be included. When specified, only these properties will be included in the response. The maximum size of this list is 50. (optional)
     * @param string   $contentType   The value for the Content-Type header. Check self::contentTypes['getProperties'] to see the possible values for this operation
     *
     * @return array of \Katanox\Model\ModelGetPropertiesResponse|\Katanox\Model\ModelApiError|\Katanox\Model\ModelInternalServerError, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws \Katanox\ApiException    on non-2xx response
     * @throws InvalidArgumentException
     */
    public function getPropertiesWithHttpInfo($authorization, $property_ids = null, string $contentType = self::contentTypes['getProperties'][0])
    {
        $request = $this->getPropertiesRequest($authorization, $property_ids, $contentType);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if ('\Katanox\Model\ModelGetPropertiesResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelGetPropertiesResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelGetPropertiesResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];

                case 400:
                    if ('\Katanox\Model\ModelApiError' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];

                case 500:
                    if ('\Katanox\Model\ModelInternalServerError' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelInternalServerError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelInternalServerError', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = '\Katanox\Model\ModelGetPropertiesResponse';
            if ('\SplFileObject' === $returnType) {
                $content = $response->getBody(); // stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ('string' !== $returnType) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelGetPropertiesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;

                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;

                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelInternalServerError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getPropertiesAsync.
     *
     * Retrieve the list of contracted properties
     *
     * @param string   $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string[] $property_ids  List of property IDs to be included. When specified, only these properties will be included in the response. The maximum size of this list is 50. (optional)
     * @param string   $contentType   The value for the Content-Type header. Check self::contentTypes['getProperties'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws InvalidArgumentException
     */
    public function getPropertiesAsync($authorization, $property_ids = null, string $contentType = self::contentTypes['getProperties'][0])
    {
        return $this->getPropertiesAsyncWithHttpInfo($authorization, $property_ids, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            )
        ;
    }

    /**
     * Operation getPropertiesAsyncWithHttpInfo.
     *
     * Retrieve the list of contracted properties
     *
     * @param string   $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string[] $property_ids  List of property IDs to be included. When specified, only these properties will be included in the response. The maximum size of this list is 50. (optional)
     * @param string   $contentType   The value for the Content-Type header. Check self::contentTypes['getProperties'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws InvalidArgumentException
     */
    public function getPropertiesAsyncWithHttpInfo($authorization, $property_ids = null, string $contentType = self::contentTypes['getProperties'][0])
    {
        $returnType = '\Katanox\Model\ModelGetPropertiesResponse';
        $request = $this->getPropertiesRequest($authorization, $property_ids, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== $returnType) {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            )
        ;
    }

    /**
     * Create request for operation 'getProperties'.
     *
     * @param string   $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string[] $property_ids  List of property IDs to be included. When specified, only these properties will be included in the response. The maximum size of this list is 50. (optional)
     * @param string   $contentType   The value for the Content-Type header. Check self::contentTypes['getProperties'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Psr7\Request
     *
     * @throws InvalidArgumentException
     */
    public function getPropertiesRequest($authorization, $property_ids = null, string $contentType = self::contentTypes['getProperties'][0])
    {
        // verify the required parameter 'authorization' is set
        if (null === $authorization || (is_array($authorization) && 0 === count($authorization))) {
            throw new InvalidArgumentException(
                'Missing the required parameter $authorization when calling getProperties'
            );
        }

        $resourcePath = '/properties';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $property_ids,
            'property_ids', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if (null !== $authorization) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost.$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPropertyById.
     *
     * Retrieve a property by id
     *
     * @param string $id            The id of the property to retrieve (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getPropertyById'] to see the possible values for this operation
     *
     * @return \Katanox\Model\ModelApiError|\Katanox\Model\ModelApiError|\Katanox\Model\ModelGetPropertyByIdResponse|\Katanox\Model\ModelInternalServerError
     *
     * @throws \Katanox\ApiException    on non-2xx response
     * @throws InvalidArgumentException
     */
    public function getPropertyById($id, $authorization, string $contentType = self::contentTypes['getPropertyById'][0])
    {
        list($response) = $this->getPropertyByIdWithHttpInfo($id, $authorization, $contentType);

        return $response;
    }

    /**
     * Operation getPropertyByIdWithHttpInfo.
     *
     * Retrieve a property by id
     *
     * @param string $id            The id of the property to retrieve (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getPropertyById'] to see the possible values for this operation
     *
     * @return array of \Katanox\Model\ModelGetPropertyByIdResponse|\Katanox\Model\ModelApiError|\Katanox\Model\ModelApiError|\Katanox\Model\ModelInternalServerError, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws \Katanox\ApiException    on non-2xx response
     * @throws InvalidArgumentException
     */
    public function getPropertyByIdWithHttpInfo($id, $authorization, string $contentType = self::contentTypes['getPropertyById'][0])
    {
        $request = $this->getPropertyByIdRequest($id, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if ('\Katanox\Model\ModelGetPropertyByIdResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelGetPropertyByIdResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelGetPropertyByIdResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];

                case 403:
                    if ('\Katanox\Model\ModelApiError' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];

                case 404:
                    if ('\Katanox\Model\ModelApiError' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];

                case 500:
                    if ('\Katanox\Model\ModelInternalServerError' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelInternalServerError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelInternalServerError', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = '\Katanox\Model\ModelGetPropertyByIdResponse';
            if ('\SplFileObject' === $returnType) {
                $content = $response->getBody(); // stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ('string' !== $returnType) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelGetPropertyByIdResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;

                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;

                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;

                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelInternalServerError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getPropertyByIdAsync.
     *
     * Retrieve a property by id
     *
     * @param string $id            The id of the property to retrieve (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getPropertyById'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws InvalidArgumentException
     */
    public function getPropertyByIdAsync($id, $authorization, string $contentType = self::contentTypes['getPropertyById'][0])
    {
        return $this->getPropertyByIdAsyncWithHttpInfo($id, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            )
        ;
    }

    /**
     * Operation getPropertyByIdAsyncWithHttpInfo.
     *
     * Retrieve a property by id
     *
     * @param string $id            The id of the property to retrieve (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getPropertyById'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws InvalidArgumentException
     */
    public function getPropertyByIdAsyncWithHttpInfo($id, $authorization, string $contentType = self::contentTypes['getPropertyById'][0])
    {
        $returnType = '\Katanox\Model\ModelGetPropertyByIdResponse';
        $request = $this->getPropertyByIdRequest($id, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== $returnType) {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            )
        ;
    }

    /**
     * Create request for operation 'getPropertyById'.
     *
     * @param string $id            The id of the property to retrieve (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getPropertyById'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Psr7\Request
     *
     * @throws InvalidArgumentException
     */
    public function getPropertyByIdRequest($id, $authorization, string $contentType = self::contentTypes['getPropertyById'][0])
    {
        // verify the required parameter 'id' is set
        if (null === $id || (is_array($id) && 0 === count($id))) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling getPropertyById'
            );
        }

        // verify the required parameter 'authorization' is set
        if (null === $authorization || (is_array($authorization) && 0 === count($authorization))) {
            throw new InvalidArgumentException(
                'Missing the required parameter $authorization when calling getPropertyById'
            );
        }

        $resourcePath = '/properties/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if (null !== $authorization) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if (null !== $id) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost.$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRateplanById.
     *
     * Retrieve a rate plan by id
     *
     * @param string $property_id   The id of the property (required)
     * @param string $id            The id of the rate plan (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getRateplanById'] to see the possible values for this operation
     *
     * @return \Katanox\Model\ModelApiError|\Katanox\Model\ModelApiError|\Katanox\Model\ModelGetRatePlanByIdResponse|\Katanox\Model\ModelInternalServerError
     *
     * @throws \Katanox\ApiException    on non-2xx response
     * @throws InvalidArgumentException
     */
    public function getRateplanById($property_id, $id, $authorization, string $contentType = self::contentTypes['getRateplanById'][0])
    {
        list($response) = $this->getRateplanByIdWithHttpInfo($property_id, $id, $authorization, $contentType);

        return $response;
    }

    /**
     * Operation getRateplanByIdWithHttpInfo.
     *
     * Retrieve a rate plan by id
     *
     * @param string $property_id   The id of the property (required)
     * @param string $id            The id of the rate plan (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getRateplanById'] to see the possible values for this operation
     *
     * @return array of \Katanox\Model\ModelGetRatePlanByIdResponse|\Katanox\Model\ModelApiError|\Katanox\Model\ModelApiError|\Katanox\Model\ModelInternalServerError, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws \Katanox\ApiException    on non-2xx response
     * @throws InvalidArgumentException
     */
    public function getRateplanByIdWithHttpInfo($property_id, $id, $authorization, string $contentType = self::contentTypes['getRateplanById'][0])
    {
        $request = $this->getRateplanByIdRequest($property_id, $id, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if ('\Katanox\Model\ModelGetRatePlanByIdResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelGetRatePlanByIdResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelGetRatePlanByIdResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];

                case 403:
                    if ('\Katanox\Model\ModelApiError' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];

                case 404:
                    if ('\Katanox\Model\ModelApiError' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];

                case 500:
                    if ('\Katanox\Model\ModelInternalServerError' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelInternalServerError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelInternalServerError', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = '\Katanox\Model\ModelGetRatePlanByIdResponse';
            if ('\SplFileObject' === $returnType) {
                $content = $response->getBody(); // stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ('string' !== $returnType) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelGetRatePlanByIdResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;

                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;

                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;

                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelInternalServerError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getRateplanByIdAsync.
     *
     * Retrieve a rate plan by id
     *
     * @param string $property_id   The id of the property (required)
     * @param string $id            The id of the rate plan (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getRateplanById'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws InvalidArgumentException
     */
    public function getRateplanByIdAsync($property_id, $id, $authorization, string $contentType = self::contentTypes['getRateplanById'][0])
    {
        return $this->getRateplanByIdAsyncWithHttpInfo($property_id, $id, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            )
        ;
    }

    /**
     * Operation getRateplanByIdAsyncWithHttpInfo.
     *
     * Retrieve a rate plan by id
     *
     * @param string $property_id   The id of the property (required)
     * @param string $id            The id of the rate plan (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getRateplanById'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws InvalidArgumentException
     */
    public function getRateplanByIdAsyncWithHttpInfo($property_id, $id, $authorization, string $contentType = self::contentTypes['getRateplanById'][0])
    {
        $returnType = '\Katanox\Model\ModelGetRatePlanByIdResponse';
        $request = $this->getRateplanByIdRequest($property_id, $id, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== $returnType) {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            )
        ;
    }

    /**
     * Create request for operation 'getRateplanById'.
     *
     * @param string $property_id   The id of the property (required)
     * @param string $id            The id of the rate plan (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getRateplanById'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Psr7\Request
     *
     * @throws InvalidArgumentException
     */
    public function getRateplanByIdRequest($property_id, $id, $authorization, string $contentType = self::contentTypes['getRateplanById'][0])
    {
        // verify the required parameter 'property_id' is set
        if (null === $property_id || (is_array($property_id) && 0 === count($property_id))) {
            throw new InvalidArgumentException(
                'Missing the required parameter $property_id when calling getRateplanById'
            );
        }

        // verify the required parameter 'id' is set
        if (null === $id || (is_array($id) && 0 === count($id))) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling getRateplanById'
            );
        }

        // verify the required parameter 'authorization' is set
        if (null === $authorization || (is_array($authorization) && 0 === count($authorization))) {
            throw new InvalidArgumentException(
                'Missing the required parameter $authorization when calling getRateplanById'
            );
        }

        $resourcePath = '/properties/{property_id}/rate-plans/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if (null !== $authorization) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if (null !== $property_id) {
            $resourcePath = str_replace(
                '{property_id}',
                ObjectSerializer::toPathValue($property_id),
                $resourcePath
            );
        }
        // path params
        if (null !== $id) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost.$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getUnitById.
     *
     * Retrieve a unit by id
     *
     * @param string $property_id   The id of the property (required)
     * @param string $id            The id of the unit (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getUnitById'] to see the possible values for this operation
     *
     * @return \Katanox\Model\ModelApiError|\Katanox\Model\ModelApiError|\Katanox\Model\ModelGetUnitByIdResponse
     *
     * @throws \Katanox\ApiException    on non-2xx response
     * @throws InvalidArgumentException
     */
    public function getUnitById($property_id, $id, $authorization, string $contentType = self::contentTypes['getUnitById'][0])
    {
        list($response) = $this->getUnitByIdWithHttpInfo($property_id, $id, $authorization, $contentType);

        return $response;
    }

    /**
     * Operation getUnitByIdWithHttpInfo.
     *
     * Retrieve a unit by id
     *
     * @param string $property_id   The id of the property (required)
     * @param string $id            The id of the unit (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getUnitById'] to see the possible values for this operation
     *
     * @return array of \Katanox\Model\ModelGetUnitByIdResponse|\Katanox\Model\ModelApiError|\Katanox\Model\ModelApiError, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws \Katanox\ApiException    on non-2xx response
     * @throws InvalidArgumentException
     */
    public function getUnitByIdWithHttpInfo($property_id, $id, $authorization, string $contentType = self::contentTypes['getUnitById'][0])
    {
        $request = $this->getUnitByIdRequest($property_id, $id, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();

            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch ($statusCode) {
                case 200:
                    if ('\Katanox\Model\ModelGetUnitByIdResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelGetUnitByIdResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelGetUnitByIdResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];

                case 404:
                    if ('\Katanox\Model\ModelApiError' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];

                case 500:
                    if ('\Katanox\Model\ModelApiError' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Katanox\Model\ModelApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Katanox\Model\ModelApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = '\Katanox\Model\ModelGetUnitByIdResponse';
            if ('\SplFileObject' === $returnType) {
                $content = $response->getBody(); // stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ('string' !== $returnType) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelGetUnitByIdResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;

                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;

                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Katanox\Model\ModelApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);

                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation getUnitByIdAsync.
     *
     * Retrieve a unit by id
     *
     * @param string $property_id   The id of the property (required)
     * @param string $id            The id of the unit (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getUnitById'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws InvalidArgumentException
     */
    public function getUnitByIdAsync($property_id, $id, $authorization, string $contentType = self::contentTypes['getUnitById'][0])
    {
        return $this->getUnitByIdAsyncWithHttpInfo($property_id, $id, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            )
        ;
    }

    /**
     * Operation getUnitByIdAsyncWithHttpInfo.
     *
     * Retrieve a unit by id
     *
     * @param string $property_id   The id of the property (required)
     * @param string $id            The id of the unit (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getUnitById'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws InvalidArgumentException
     */
    public function getUnitByIdAsyncWithHttpInfo($property_id, $id, $authorization, string $contentType = self::contentTypes['getUnitById'][0])
    {
        $returnType = '\Katanox\Model\ModelGetUnitByIdResponse';
        $request = $this->getUnitByIdRequest($property_id, $id, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== $returnType) {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            )
        ;
    }

    /**
     * Create request for operation 'getUnitById'.
     *
     * @param string $property_id   The id of the property (required)
     * @param string $id            The id of the unit (required)
     * @param string $authorization Type &#39;Bearer&#39; and then your API Token (required)
     * @param string $contentType   The value for the Content-Type header. Check self::contentTypes['getUnitById'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Psr7\Request
     *
     * @throws InvalidArgumentException
     */
    public function getUnitByIdRequest($property_id, $id, $authorization, string $contentType = self::contentTypes['getUnitById'][0])
    {
        // verify the required parameter 'property_id' is set
        if (null === $property_id || (is_array($property_id) && 0 === count($property_id))) {
            throw new InvalidArgumentException(
                'Missing the required parameter $property_id when calling getUnitById'
            );
        }

        // verify the required parameter 'id' is set
        if (null === $id || (is_array($id) && 0 === count($id))) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling getUnitById'
            );
        }

        // verify the required parameter 'authorization' is set
        if (null === $authorization || (is_array($authorization) && 0 === count($authorization))) {
            throw new InvalidArgumentException(
                'Missing the required parameter $authorization when calling getUnitById'
            );
        }

        $resourcePath = '/properties/{property_id}/units/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if (null !== $authorization) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if (null !== $property_id) {
            $resourcePath = str_replace(
                '{property_id}',
                ObjectSerializer::toPathValue($property_id),
                $resourcePath
            );
        }
        // path params
        if (null !== $id) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost.$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option.
     *
     * @return array of http client options
     *
     * @throws RuntimeException on file opening failure
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new RuntimeException('Failed to open the debug file: '.$this->config->getDebugFile());
            }
        }

        return $options;
    }
}
