<?php
/**
 * PolicyPolicyType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Katanox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Katanox API Documentation
 *
 * The Katanox API allows any travel seller to search and book accommodation.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Katanox\Model;
use \Katanox\ObjectSerializer;

/**
 * PolicyPolicyType Class Doc Comment
 *
 * @category Class
 * @package  Katanox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PolicyPolicyType
{
    /**
     * Possible values of this enum
     */
    public const STATIC_POLICY_TYPE = 'static';

    public const DYNAMIC_POLICY_TYPE = 'dynamic';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STATIC_POLICY_TYPE,
            self::DYNAMIC_POLICY_TYPE
        ];
    }
}


