<?php
/**
 * AvailabilityOffersDataTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Katanox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Katanox API Documentation
 *
 * The Katanox API allows any travel seller to search and book accommodation.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Katanox\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AvailabilityOffersDataTest Class Doc Comment
 *
 * @category    Class
 * @description AvailabilityOffersData
 * @package     Katanox
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AvailabilityOffersDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AvailabilityOffersData"
     */
    public function testAvailabilityOffersData()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "number_of_units"
     */
    public function testPropertyNumberOfUnits()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "offers"
     */
    public function testPropertyOffers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
